// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Livraria.API.Migrations
{
    [DbContext(typeof(LivrariaDbContext))]
    [Migration("20231013032854_v1-1")]
    partial class v11
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(56)
                        .HasColumnType("TEXT")
                        .HasColumnName("lv_autor");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("lv_img");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("lv_idioma");

                    b.Property<int>("Pages")
                        .HasColumnType("INTEGER")
                        .HasColumnName("lv_paginas");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("lv_datapublicacao");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("lv_publicadora");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("lv_titulo");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
